# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/rvladimir/ami-Vladimir-Rodin-thisarivson

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/rvladimir/ami-Vladimir-Rodin-thisarivson

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(CMAKE_COMMAND) -E cmake_progress_start /Users/rvladimir/ami-Vladimir-Rodin-thisarivson/CMakeFiles /Users/rvladimir/ami-Vladimir-Rodin-thisarivson/tasks/image_processor//CMakeFiles/progress.marks
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/rvladimir/ami-Vladimir-Rodin-thisarivson/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
tasks/image_processor/CMakeFiles/image_processor.dir/rule:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/CMakeFiles/image_processor.dir/rule
.PHONY : tasks/image_processor/CMakeFiles/image_processor.dir/rule

# Convenience name for target.
image_processor: tasks/image_processor/CMakeFiles/image_processor.dir/rule
.PHONY : image_processor

# fast build rule for target.
image_processor/fast:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/build
.PHONY : image_processor/fast

# Convenience name for target.
tasks/image_processor/CMakeFiles/test_parser.dir/rule:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/CMakeFiles/test_parser.dir/rule
.PHONY : tasks/image_processor/CMakeFiles/test_parser.dir/rule

# Convenience name for target.
test_parser: tasks/image_processor/CMakeFiles/test_parser.dir/rule
.PHONY : test_parser

# fast build rule for target.
test_parser/fast:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/build
.PHONY : test_parser/fast

# Convenience name for target.
tasks/image_processor/CMakeFiles/test_io.dir/rule:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/CMakeFiles/test_io.dir/rule
.PHONY : tasks/image_processor/CMakeFiles/test_io.dir/rule

# Convenience name for target.
test_io: tasks/image_processor/CMakeFiles/test_io.dir/rule
.PHONY : test_io

# fast build rule for target.
test_io/fast:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/build
.PHONY : test_io/fast

# Convenience name for target.
tasks/image_processor/CMakeFiles/test_controller.dir/rule:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks/image_processor/CMakeFiles/test_controller.dir/rule
.PHONY : tasks/image_processor/CMakeFiles/test_controller.dir/rule

# Convenience name for target.
test_controller: tasks/image_processor/CMakeFiles/test_controller.dir/rule
.PHONY : test_controller

# fast build rule for target.
test_controller/fast:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/build
.PHONY : test_controller/fast

controller.o: controller.cpp.o
.PHONY : controller.o

# target to build an object file
controller.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/controller.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/controller.cpp.o
.PHONY : controller.cpp.o

controller.i: controller.cpp.i
.PHONY : controller.i

# target to preprocess a source file
controller.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/controller.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/controller.cpp.i
.PHONY : controller.cpp.i

controller.s: controller.cpp.s
.PHONY : controller.s

# target to generate assembly for a file
controller.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/controller.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/controller.cpp.s
.PHONY : controller.cpp.s

filters/affine_tile.o: filters/affine_tile.cpp.o
.PHONY : filters/affine_tile.o

# target to build an object file
filters/affine_tile.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/affine_tile.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/affine_tile.cpp.o
.PHONY : filters/affine_tile.cpp.o

filters/affine_tile.i: filters/affine_tile.cpp.i
.PHONY : filters/affine_tile.i

# target to preprocess a source file
filters/affine_tile.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/affine_tile.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/affine_tile.cpp.i
.PHONY : filters/affine_tile.cpp.i

filters/affine_tile.s: filters/affine_tile.cpp.s
.PHONY : filters/affine_tile.s

# target to generate assembly for a file
filters/affine_tile.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/affine_tile.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/affine_tile.cpp.s
.PHONY : filters/affine_tile.cpp.s

filters/blur.o: filters/blur.cpp.o
.PHONY : filters/blur.o

# target to build an object file
filters/blur.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/blur.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/blur.cpp.o
.PHONY : filters/blur.cpp.o

filters/blur.i: filters/blur.cpp.i
.PHONY : filters/blur.i

# target to preprocess a source file
filters/blur.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/blur.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/blur.cpp.i
.PHONY : filters/blur.cpp.i

filters/blur.s: filters/blur.cpp.s
.PHONY : filters/blur.s

# target to generate assembly for a file
filters/blur.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/blur.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/blur.cpp.s
.PHONY : filters/blur.cpp.s

filters/crop.o: filters/crop.cpp.o
.PHONY : filters/crop.o

# target to build an object file
filters/crop.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/crop.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/crop.cpp.o
.PHONY : filters/crop.cpp.o

filters/crop.i: filters/crop.cpp.i
.PHONY : filters/crop.i

# target to preprocess a source file
filters/crop.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/crop.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/crop.cpp.i
.PHONY : filters/crop.cpp.i

filters/crop.s: filters/crop.cpp.s
.PHONY : filters/crop.s

# target to generate assembly for a file
filters/crop.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/crop.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/crop.cpp.s
.PHONY : filters/crop.cpp.s

filters/edge_detection.o: filters/edge_detection.cpp.o
.PHONY : filters/edge_detection.o

# target to build an object file
filters/edge_detection.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/edge_detection.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/edge_detection.cpp.o
.PHONY : filters/edge_detection.cpp.o

filters/edge_detection.i: filters/edge_detection.cpp.i
.PHONY : filters/edge_detection.i

# target to preprocess a source file
filters/edge_detection.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/edge_detection.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/edge_detection.cpp.i
.PHONY : filters/edge_detection.cpp.i

filters/edge_detection.s: filters/edge_detection.cpp.s
.PHONY : filters/edge_detection.s

# target to generate assembly for a file
filters/edge_detection.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/edge_detection.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/edge_detection.cpp.s
.PHONY : filters/edge_detection.cpp.s

filters/grayscale.o: filters/grayscale.cpp.o
.PHONY : filters/grayscale.o

# target to build an object file
filters/grayscale.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/grayscale.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/grayscale.cpp.o
.PHONY : filters/grayscale.cpp.o

filters/grayscale.i: filters/grayscale.cpp.i
.PHONY : filters/grayscale.i

# target to preprocess a source file
filters/grayscale.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/grayscale.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/grayscale.cpp.i
.PHONY : filters/grayscale.cpp.i

filters/grayscale.s: filters/grayscale.cpp.s
.PHONY : filters/grayscale.s

# target to generate assembly for a file
filters/grayscale.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/grayscale.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/grayscale.cpp.s
.PHONY : filters/grayscale.cpp.s

filters/negative.o: filters/negative.cpp.o
.PHONY : filters/negative.o

# target to build an object file
filters/negative.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/negative.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/negative.cpp.o
.PHONY : filters/negative.cpp.o

filters/negative.i: filters/negative.cpp.i
.PHONY : filters/negative.i

# target to preprocess a source file
filters/negative.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/negative.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/negative.cpp.i
.PHONY : filters/negative.cpp.i

filters/negative.s: filters/negative.cpp.s
.PHONY : filters/negative.s

# target to generate assembly for a file
filters/negative.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/negative.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/negative.cpp.s
.PHONY : filters/negative.cpp.s

filters/sharpering.o: filters/sharpering.cpp.o
.PHONY : filters/sharpering.o

# target to build an object file
filters/sharpering.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/sharpering.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/sharpering.cpp.o
.PHONY : filters/sharpering.cpp.o

filters/sharpering.i: filters/sharpering.cpp.i
.PHONY : filters/sharpering.i

# target to preprocess a source file
filters/sharpering.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/sharpering.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/sharpering.cpp.i
.PHONY : filters/sharpering.cpp.i

filters/sharpering.s: filters/sharpering.cpp.s
.PHONY : filters/sharpering.s

# target to generate assembly for a file
filters/sharpering.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/filters/sharpering.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/filters/sharpering.cpp.s
.PHONY : filters/sharpering.cpp.s

image.o: image.cpp.o
.PHONY : image.o

# target to build an object file
image.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/image.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/image.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/image.cpp.o
.PHONY : image.cpp.o

image.i: image.cpp.i
.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/image.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/image.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s
.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/image.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/image.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/image.cpp.s
.PHONY : image.cpp.s

image_processor.o: image_processor.cpp.o
.PHONY : image_processor.o

# target to build an object file
image_processor.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/image_processor.cpp.o
.PHONY : image_processor.cpp.o

image_processor.i: image_processor.cpp.i
.PHONY : image_processor.i

# target to preprocess a source file
image_processor.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/image_processor.cpp.i
.PHONY : image_processor.cpp.i

image_processor.s: image_processor.cpp.s
.PHONY : image_processor.s

# target to generate assembly for a file
image_processor.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/image_processor.cpp.s
.PHONY : image_processor.cpp.s

io.o: io.cpp.o
.PHONY : io.o

# target to build an object file
io.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/io.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/io.cpp.o
.PHONY : io.cpp.o

io.i: io.cpp.i
.PHONY : io.i

# target to preprocess a source file
io.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/io.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/io.cpp.i
.PHONY : io.cpp.i

io.s: io.cpp.s
.PHONY : io.s

# target to generate assembly for a file
io.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/io.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/io.cpp.s
.PHONY : io.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/parser.cpp.o
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/parser.cpp.i
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/image_processor.dir/build.make tasks/image_processor/CMakeFiles/image_processor.dir/parser.cpp.s
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/parser.cpp.s
.PHONY : parser.cpp.s

test_controller.o: test_controller.cpp.o
.PHONY : test_controller.o

# target to build an object file
test_controller.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/test_controller.cpp.o
.PHONY : test_controller.cpp.o

test_controller.i: test_controller.cpp.i
.PHONY : test_controller.i

# target to preprocess a source file
test_controller.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/test_controller.cpp.i
.PHONY : test_controller.cpp.i

test_controller.s: test_controller.cpp.s
.PHONY : test_controller.s

# target to generate assembly for a file
test_controller.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_controller.dir/build.make tasks/image_processor/CMakeFiles/test_controller.dir/test_controller.cpp.s
.PHONY : test_controller.cpp.s

test_io.o: test_io.cpp.o
.PHONY : test_io.o

# target to build an object file
test_io.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/test_io.cpp.o
.PHONY : test_io.cpp.o

test_io.i: test_io.cpp.i
.PHONY : test_io.i

# target to preprocess a source file
test_io.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/test_io.cpp.i
.PHONY : test_io.cpp.i

test_io.s: test_io.cpp.s
.PHONY : test_io.s

# target to generate assembly for a file
test_io.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_io.dir/build.make tasks/image_processor/CMakeFiles/test_io.dir/test_io.cpp.s
.PHONY : test_io.cpp.s

test_parser.o: test_parser.cpp.o
.PHONY : test_parser.o

# target to build an object file
test_parser.cpp.o:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/test_parser.cpp.o
.PHONY : test_parser.cpp.o

test_parser.i: test_parser.cpp.i
.PHONY : test_parser.i

# target to preprocess a source file
test_parser.cpp.i:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/test_parser.cpp.i
.PHONY : test_parser.cpp.i

test_parser.s: test_parser.cpp.s
.PHONY : test_parser.s

# target to generate assembly for a file
test_parser.cpp.s:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(MAKE) $(MAKESILENT) -f tasks/image_processor/CMakeFiles/test_parser.dir/build.make tasks/image_processor/CMakeFiles/test_parser.dir/test_parser.cpp.s
.PHONY : test_parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_processor"
	@echo "... test_controller"
	@echo "... test_io"
	@echo "... test_parser"
	@echo "... controller.o"
	@echo "... controller.i"
	@echo "... controller.s"
	@echo "... filters/affine_tile.o"
	@echo "... filters/affine_tile.i"
	@echo "... filters/affine_tile.s"
	@echo "... filters/blur.o"
	@echo "... filters/blur.i"
	@echo "... filters/blur.s"
	@echo "... filters/crop.o"
	@echo "... filters/crop.i"
	@echo "... filters/crop.s"
	@echo "... filters/edge_detection.o"
	@echo "... filters/edge_detection.i"
	@echo "... filters/edge_detection.s"
	@echo "... filters/grayscale.o"
	@echo "... filters/grayscale.i"
	@echo "... filters/grayscale.s"
	@echo "... filters/negative.o"
	@echo "... filters/negative.i"
	@echo "... filters/negative.s"
	@echo "... filters/sharpering.o"
	@echo "... filters/sharpering.i"
	@echo "... filters/sharpering.s"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
	@echo "... image_processor.o"
	@echo "... image_processor.i"
	@echo "... image_processor.s"
	@echo "... io.o"
	@echo "... io.i"
	@echo "... io.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... test_controller.o"
	@echo "... test_controller.i"
	@echo "... test_controller.s"
	@echo "... test_io.o"
	@echo "... test_io.i"
	@echo "... test_io.s"
	@echo "... test_parser.o"
	@echo "... test_parser.i"
	@echo "... test_parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/rvladimir/ami-Vladimir-Rodin-thisarivson && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

